version: '3'
services:

  mongo:
    image: 'mongo:3.4.1'
    container_name: 'mongo'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'
  rabbitmq:
    image: rabbitmq:management
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
  trip-management-query:
    build: ./
    ports:
      - '8085:8085'
    depends_on:
      - rabbitmq
      - mongo

volumes:
  mongo:
