version: '3'
services:

  mongo:
    image: 'mongo:3.4.1'
    container_name: 'mongo'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'
  rabbitmq:
    image: rabbitmq:management
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
  trip-management-cmd:
    image: aista/trip-management-cmd
    container_name: 'trip-management-cmd'
    environment:
      - RABBIT_HOST=rabbitmq
      - MONGO_HOST=mongo
    ports:
      - "9000:8080"
    depends_on:
      - rabbitmq
      - mongo
  trip-management-query:
    build: ./
    container_name: 'trip-management-query'
    environment:
      - RABBIT_HOST=rabbitmq
      - MONGO_HOST=mongo
    ports:
      - '9001:8080'
    depends_on:
      - rabbitmq
      - mongo
      - trip-management-cmd
volumes:
  mongo:
