version: '3'
services:

  mongo:
    image: 'mongo:3.4.1'
    container_name: 'mongo'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'
  rabbitmq:
    image: rabbitmq:management
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
  tripmanagementcmd:
    image: aista/trip-management-cmd
    environment:
      - RABBIT_HOST=rabbitmq
      - MONGO_HOST=mongo
    ports:
      - "8080"
    depends_on:
      - rabbitmq
      - mongo
      - discovery-service
  discovery-service:
    image: springcloud/eureka
    ports:
      - "8761:8761"

volumes:
  mongo:
